server.port=8083
spring.application.name=subscription-service

spring.datasource.url=jdbc:mysql://paytracker-db.cxs208kqq876.eu-north-1.rds.amazonaws.com:3306/subscription_db
spring.datasource.username=admin
spring.datasource.password=ssaword45678
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest